@include('admin.adminLayout.partials.header')
@include('admin.adminLayout.partials.sidebar')
@include('admin.adminLayout.partials.topNav')
@yield('contents')
@include('admin.adminLayout.partials.footer')
